Add ability to reuse same component multiple times in the same view
AaronErhardt/relm4 pull request #27
Opened 2021-09-15 19:41 UTC by mskorkowski

Solution for #25

2021-09-15 20:00 UTC, AaronErhardt requested changes
Thanks a lot! Looks pretty good overall, just enabling the tracker features again would be nice, most notable un-commenting all places where `self.reset()` was used.

2021-09-15 20:21 UTC, mskorkowski commented on relm4-components/src/alert.rs
> +    _conf_provider: PhantomData<*const Conf>,
As PahntomData doc says `PhantomData<T>` indicates ownership of T, and `PhantomData<&'a T>` or `PhantomData<*const T>` does not.

https://docs.rs/rustc-std-workspace-std/1.0.1/std/marker/struct.PhantomData.html#ownership-and-the-drop-check

2021-09-15 20:27 UTC, mskorkowski commented on src/lib.rs
> +#![feature(doc_cfg)]
Of course. It was complaining while I was compiling doc comments

2021-09-15 20:31 UTC, AaronErhardt commented on src/lib.rs
> +#![feature(doc_cfg)]
Yeah the docs are a bit weird right now. They only work in nightly and are deployed by a custom script. Hopefully this feature will be stabilised soon.

2021-09-15 20:35 UTC, mskorkowski commented
All should be fixed

2021-09-16 18:43 UTC, AaronErhardt approved these changes
Thanks a lot for your contribution!!

2021-09-16 18:43 UTC, merged